// Pre-built workflow templates

export const WORKFLOW_TEMPLATES = {
  SIMPLE_APPROVAL: {
    name: 'Simple Approval Workflow',
    code: 'SIMPLE_APPROVAL',
    description:
      'Basic workflow: Inward → Section Officer → Approval Authority → Dispatch',
    category: 'approval',
    templateData: {
      nodes: [
        {
          id: 'start',
          nodeId: 'start',
          nodeType: 'start',
          label: 'Start',
          positionX: 100,
          positionY: 200,
        },
        {
          id: 'inward',
          nodeId: 'inward',
          nodeType: 'task',
          label: 'Inward Desk',
          assigneeType: 'role',
          assigneeValue: 'INWARD_DESK',
          timeLimit: 86400, // 1 day
          availableActions: ['forward', 'return'],
          positionX: 300,
          positionY: 200,
        },
        {
          id: 'section_officer',
          nodeId: 'section_officer',
          nodeType: 'task',
          label: 'Section Officer',
          assigneeType: 'role',
          assigneeValue: 'SECTION_OFFICER',
          timeLimit: 259200, // 3 days
          availableActions: ['forward', 'return', 'request_opinion'],
          positionX: 500,
          positionY: 200,
        },
        {
          id: 'approval',
          nodeId: 'approval',
          nodeType: 'task',
          label: 'Approval Authority',
          assigneeType: 'role',
          assigneeValue: 'APPROVAL_AUTHORITY',
          timeLimit: 172800, // 2 days
          availableActions: ['approve', 'reject', 'return'],
          positionX: 700,
          positionY: 200,
        },
        {
          id: 'decision',
          nodeId: 'decision',
          nodeType: 'decision',
          label: 'Approved?',
          positionX: 900,
          positionY: 200,
        },
        {
          id: 'dispatch',
          nodeId: 'dispatch',
          nodeType: 'task',
          label: 'Dispatch',
          assigneeType: 'role',
          assigneeValue: 'DISPATCHER',
          timeLimit: 86400, // 1 day
          availableActions: ['dispatch'],
          positionX: 1100,
          positionY: 100,
        },
        {
          id: 'end',
          nodeId: 'end',
          nodeType: 'end',
          label: 'End',
          positionX: 1300,
          positionY: 100,
        },
        {
          id: 'rejected',
          nodeId: 'rejected',
          nodeType: 'end',
          label: 'Rejected',
          positionX: 1100,
          positionY: 300,
        },
      ],
      edges: [
        { sourceNodeId: 'start', targetNodeId: 'inward', label: '' },
        {
          sourceNodeId: 'inward',
          targetNodeId: 'section_officer',
          label: 'Forward',
        },
        {
          sourceNodeId: 'section_officer',
          targetNodeId: 'approval',
          label: 'Forward',
        },
        { sourceNodeId: 'approval', targetNodeId: 'decision', label: '' },
        {
          sourceNodeId: 'decision',
          targetNodeId: 'dispatch',
          label: 'Approved',
          condition: { field: 'action', operator: 'equals', value: 'approve' },
          priority: 1,
        },
        {
          sourceNodeId: 'decision',
          targetNodeId: 'rejected',
          label: 'Rejected',
          condition: { field: 'action', operator: 'equals', value: 'reject' },
          priority: 0,
        },
        { sourceNodeId: 'dispatch', targetNodeId: 'end', label: 'Dispatched' },
      ],
    },
  },

  CONSULTATION_WORKFLOW: {
    name: 'Consultation Workflow',
    code: 'CONSULTATION_WORKFLOW',
    description: 'Workflow with opinion/consultation branch',
    category: 'consultation',
    templateData: {
      nodes: [
        {
          id: 'start',
          nodeId: 'start',
          nodeType: 'start',
          label: 'Start',
          positionX: 100,
          positionY: 200,
        },
        {
          id: 'section_officer',
          nodeId: 'section_officer',
          nodeType: 'task',
          label: 'Section Officer',
          assigneeType: 'role',
          assigneeValue: 'SECTION_OFFICER',
          timeLimit: 259200,
          availableActions: ['forward', 'request_opinion'],
          positionX: 300,
          positionY: 200,
        },
        {
          id: 'opinion_decision',
          nodeId: 'opinion_decision',
          nodeType: 'decision',
          label: 'Opinion Required?',
          positionX: 500,
          positionY: 200,
        },
        {
          id: 'opinion_desk',
          nodeId: 'opinion_desk',
          nodeType: 'task',
          label: 'Opinion Desk',
          assigneeType: 'department',
          assigneeValue: '', // Set dynamically
          timeLimit: 172800,
          availableActions: ['provide_opinion'],
          positionX: 500,
          positionY: 350,
        },
        {
          id: 'approval',
          nodeId: 'approval',
          nodeType: 'task',
          label: 'Approval Authority',
          assigneeType: 'role',
          assigneeValue: 'APPROVAL_AUTHORITY',
          timeLimit: 172800,
          availableActions: ['approve', 'reject'],
          positionX: 700,
          positionY: 200,
        },
        {
          id: 'end',
          nodeId: 'end',
          nodeType: 'end',
          label: 'End',
          positionX: 900,
          positionY: 200,
        },
      ],
      edges: [
        { sourceNodeId: 'start', targetNodeId: 'section_officer' },
        { sourceNodeId: 'section_officer', targetNodeId: 'opinion_decision' },
        {
          sourceNodeId: 'opinion_decision',
          targetNodeId: 'opinion_desk',
          label: 'Yes',
          condition: {
            field: 'action',
            operator: 'equals',
            value: 'request_opinion',
          },
        },
        {
          sourceNodeId: 'opinion_decision',
          targetNodeId: 'approval',
          label: 'No',
          condition: { field: 'action', operator: 'equals', value: 'forward' },
        },
        {
          sourceNodeId: 'opinion_desk',
          targetNodeId: 'approval',
          label: 'Opinion Provided',
        },
        { sourceNodeId: 'approval', targetNodeId: 'end' },
      ],
    },
  },

  MULTI_LEVEL_APPROVAL: {
    name: 'Multi-Level Approval',
    code: 'MULTI_LEVEL_APPROVAL',
    description: 'Workflow with multiple approval levels',
    category: 'approval',
    templateData: {
      nodes: [
        {
          id: 'start',
          nodeId: 'start',
          nodeType: 'start',
          label: 'Start',
          positionX: 100,
          positionY: 200,
        },
        {
          id: 'inward',
          nodeId: 'inward',
          nodeType: 'task',
          label: 'Inward Desk',
          assigneeType: 'role',
          assigneeValue: 'INWARD_DESK',
          timeLimit: 86400,
          availableActions: ['forward'],
          positionX: 300,
          positionY: 200,
        },
        {
          id: 'section_officer',
          nodeId: 'section_officer',
          nodeType: 'task',
          label: 'Section Officer',
          assigneeType: 'role',
          assigneeValue: 'SECTION_OFFICER',
          timeLimit: 259200,
          availableActions: ['forward', 'return'],
          positionX: 500,
          positionY: 200,
        },
        {
          id: 'dept_admin',
          nodeId: 'dept_admin',
          nodeType: 'task',
          label: 'Department Admin',
          assigneeType: 'role',
          assigneeValue: 'DEPT_ADMIN',
          timeLimit: 172800,
          availableActions: ['approve', 'reject', 'return'],
          positionX: 700,
          positionY: 200,
        },
        {
          id: 'approval_authority',
          nodeId: 'approval_authority',
          nodeType: 'task',
          label: 'Approval Authority',
          assigneeType: 'role',
          assigneeValue: 'APPROVAL_AUTHORITY',
          timeLimit: 172800,
          availableActions: ['approve', 'reject', 'return'],
          positionX: 900,
          positionY: 200,
        },
        {
          id: 'dispatch',
          nodeId: 'dispatch',
          nodeType: 'task',
          label: 'Dispatch',
          assigneeType: 'role',
          assigneeValue: 'DISPATCHER',
          timeLimit: 86400,
          availableActions: ['dispatch'],
          positionX: 1100,
          positionY: 200,
        },
        {
          id: 'end',
          nodeId: 'end',
          nodeType: 'end',
          label: 'End',
          positionX: 1300,
          positionY: 200,
        },
      ],
      edges: [
        { sourceNodeId: 'start', targetNodeId: 'inward' },
        { sourceNodeId: 'inward', targetNodeId: 'section_officer' },
        { sourceNodeId: 'section_officer', targetNodeId: 'dept_admin' },
        { sourceNodeId: 'dept_admin', targetNodeId: 'approval_authority' },
        { sourceNodeId: 'approval_authority', targetNodeId: 'dispatch' },
        { sourceNodeId: 'dispatch', targetNodeId: 'end' },
      ],
    },
  },
};
